// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBBhjAB-drpCxCZe3W6jaDmbRC37g7On8',
    appId: '1:507397871783:web:dac30afbc1aef08b05e382',
    messagingSenderId: '507397871783',
    projectId: 'nslink-meeting-side',
    authDomain: 'nslink-meeting-side.firebaseapp.com',
    databaseURL: 'https://nslink-meeting-side-default-rtdb.firebaseio.com',
    storageBucket: 'nslink-meeting-side.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTca08WHkZ5xJSypfK6Y52pWDRlAMHj10',
    appId: '1:507397871783:android:30586dedd1b7dfab05e382',
    messagingSenderId: '507397871783',
    projectId: 'nslink-meeting-side',
    databaseURL: 'https://nslink-meeting-side-default-rtdb.firebaseio.com',
    storageBucket: 'nslink-meeting-side.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFiv9w406abAel-xD8-KxMDRy5IfZwLn4',
    appId: '1:507397871783:ios:52b6a00d1abc6f3005e382',
    messagingSenderId: '507397871783',
    projectId: 'nslink-meeting-side',
    databaseURL: 'https://nslink-meeting-side-default-rtdb.firebaseio.com',
    storageBucket: 'nslink-meeting-side.firebasestorage.app',
    iosBundleId: 'com.example.lectureBookingPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFiv9w406abAel-xD8-KxMDRy5IfZwLn4',
    appId: '1:507397871783:ios:52b6a00d1abc6f3005e382',
    messagingSenderId: '507397871783',
    projectId: 'nslink-meeting-side',
    databaseURL: 'https://nslink-meeting-side-default-rtdb.firebaseio.com',
    storageBucket: 'nslink-meeting-side.firebasestorage.app',
    iosBundleId: 'com.example.lectureBookingPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBBhjAB-drpCxCZe3W6jaDmbRC37g7On8',
    appId: '1:507397871783:web:3093daab6e696a0205e382',
    messagingSenderId: '507397871783',
    projectId: 'nslink-meeting-side',
    authDomain: 'nslink-meeting-side.firebaseapp.com',
    databaseURL: 'https://nslink-meeting-side-default-rtdb.firebaseio.com',
    storageBucket: 'nslink-meeting-side.firebasestorage.app',
  );
}
